#### Basics of NumPy Arrays
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. Unlike Python's built-in lists NumPy arrays provide efficient storage and faster processing for numerical and scientific computations. It offers functions for linear algebra and random number generation making it important for data science and machine learning.
</div>

#### Types of Array
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
1. One Dimensional Array: Stores elements in a single row. It is the simplest type of NumPy array and is commonly used to represent a sequence of values.<br>
2. Multi-Dimensional Array: Stores data in two or more dimensions. The most common type is a two-dimensional array, which organizes data into rows and columns.
</div>

In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3, 4]
arr = np.array(a)

print("List: ", a)
print("Numpy Array:", arr)
print(type(a))
print(type(arr))

List:  [1, 2, 3, 4]
Numpy Array: [1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]
l3 = [9, 10, 11, 12]
arr = np.array([l1, l2, l3])
print(arr)
# Each inner list represents a row in the array.
# np.array() combines the lists into a two-dimensional NumPy array.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Parameters of a Numpy Array
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
1. Axis: represents a dimension of an array.<br>
<pre>
        Axis 0 -> Rows (first dimension)
        Axis 1 -> Columns (second dimension)
        Axis 2 -> Third dimension in a 3D array
</pre>
2. Shape: indicates the number of elements along each dimension. It is returned as a tuple.<br>
3. Rank: number of dimensions (axes) it has.<br>
<pre>
        A one-dimensional array has rank 1.
        A two-dimensional array has rank 2.
        A three-dimensional array has rank 3.
</pre>
4. Data Type (dtype): property specifies the type of data stored in an array, such as integers, floating-point numbers, or strings.
</div>

In [ ]:
arr = np.array([
    [0, 4, 2],
    [3, 4, 5],
    [23, 4, 5],
    [2, 34, 5],
    [5, 6, 7]]
)
print(arr.shape)
# array contains 5 rows and 3 columns. Therefore, arr.shape returns (5, 3)

(5, 3)


In [ ]:
arr1 = np.array([[0, 4, 2]])
arr2 = np.array([0.2, 0.4, 2.4])
print("Data type of array 1:", arr1.dtype)
print("Data type of array 2:", arr2.dtype)

Data type of array 1: int64
Data type of array 2: float64


#### Different Ways of Creating Numpy Array
<pre style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
1. numpy.array(): creates a NumPy array from Python sequences such as lists or tuples.
2. numpy.fromiter(): creates a one-dimensional array from an iterable object.
3. numpy.arange(): returns evenly spaced values within a specified range.
4. numpy.linspace(): returns a specified number of evenly spaced values between two limits.
5. numpy.empty(): creates an array of a given shape without initializing its values.
6. numpy.ones(): creates an array filled with ones.
7. numpy.zeros(): creates an array filled with zeros.
8. numpy.full(): Creates an array filled with a specified value.
</pre>


In [ ]:
l = [1, 2, 3, 4, 5]
arr1 = np.array(l)
arr2 = np.array([3, 4, 5, 5])
print(arr1)
print(arr2)

[1 2 3 4 5]
[3 4 5 5]


In [ ]:
text = "GeeksforGeeks"
arr = np.fromiter(text, dtype="U2")
print(arr)

['G' 'e' 'e' 'k' 's' 'f' 'o' 'r' 'G' 'e' 'e' 'k' 's']


In [ ]:
arr = np.arange(1, 20, 2, dtype=np.float32)
print(arr)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


In [ ]:
arr = np.linspace(3.5, 10, 3, dtype=np.int32)
print(arr)

[ 3  6 10]


In [ ]:
arr = np.empty((4, 3), dtype=np.int32)
print(arr)

[[ 7  0  8]
 [ 0  9  0]
 [10  0 11]
 [ 0 12  0]]


In [ ]:
arr = np.ones((4, 3), dtype=np.int32)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr = np.zeros((4, 3), dtype=np.int32)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr = np.full((3, 3), 8)
print(arr)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


#### Create Numpy Arrays Using Random Number
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
1. np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1). <br>
2. np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution. <br>
3. np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.
</div>

In [ ]:
arr1 = np.random.rand(3, 3)     # uniform distribution
arr2 = np.random.randn(3, 3)    # standard normal distribution
arr3 = np.random.randint(1, 10, size=(3, 4))  
print(arr3)

[[9 8 9 1]
 [9 7 1 9]
 [7 4 7 7]]


#### Create Numpy Arrays Using Matrix Creation Routines
<pre style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
NumPy provides functions to create specific types of matrices.
1. np.eye(): Creates an identity matrix of specified size.
2. np.diag(): Constructs a diagonal array.
3. np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
4. np.ones_like(): Creates an array of ones with the same shape and type as a given array.
</pre>


In [ ]:
iden = np.eye(3)
diag = np.diag([1, 2, 3])
arr0 = np.zeros_like(iden)
arr1 = np.ones_like(diag)

print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Numpy Array Indexing
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
Array indexing in NumPy refers to the method of accessing specific elements or subsets of data within an array. This feature allows us to retrieve, modify and manipulate data at specific positions or ranges helps in making it easier to work with large datasets.<br>
1. Accessing Elements in 1D Arrays<br>
2. Accessing Elements in Multidimensional Arrays<br>
<pre>
      3D Arrays: It can be visualized as a stack of 2D arrays, we need three indices-
      Depth: Specifies the 2D slice.
      Row: Specifies the row within the slice.
      Column: Specifies the column within the row.
</pre><br>
3. Slicing Arrays: It allows us to extract a range of elements using the format (start:stop:step).<br>
4. Boolean Indexing: It allows us to filter elements from an array based on a condition and returns only those that meet it.<br>
5. Fancy Indexing: It is also known as Advanced Indexing which allows us access elements of an array by using another array or list of indices. This allows selecting multiple elements at once from different positions in the array.<br>
6. Integer Array Indexing: It is similar to fancy indexing and uses an array of integers to select multiple elements from another array.<br>
7. Ellipsis (...) in Indexing: The ellipsis (...) can be used to select all dimensions which are not explicitly mentioned. This is helpful in multidimensional arrays when we don’t want to specify every dimension.
</div>

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])

10
50


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[1, 2])
print(matrix[-2, -1])

6
6


In [ ]:
cube = np.array([
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]],

    [[10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]]
])
print(cube[1, 1, 1])

14


In [ ]:
# 3. Slicing Arrays:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[1:4])
print(arr[-4:-1])

[1 2 3]
[2 3 4]


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[0:2, 1:3])
print(matrix[-2:, -3:-1])

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


In [ ]:
cube = np.array([
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]],

    [[10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]]
])
print(cube[0:1, 0:2, 0:3])

[[[1 2 3]
  [4 5 6]]]


In [ ]:
# 4. Boolean Indexing
arr = np.array([10, 15, 20, 25, 30])
print(arr[arr > 20])

[25 30]


In [ ]:
# 5. Fancy Indexing (Advanced Indexing)
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])
print(arr[[0, 2, 4]])   # 6. Integer Array Indexing

[10 30 50]
[10 30 50]


In [ ]:
# 7. Ellipsis (...) in Indexing
cube = np.random.rand(3, 3, 3)
print(cube[..., 0])

[[0.52048868 0.59672595 0.6141365 ]
 [0.09841798 0.83040477 0.74712958]
 [0.96830398 0.51182448 0.68644009]]


In [ ]:
# 8. Using np.newaxis to Add New Dimensions
# The np.newaxis keyword adds a new axis to the array which helps in converting a 1D array into a row or column vector.

arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


In [ ]:
# 9. Modifying Array Elements
# We can modify array elements directly by using indexing or slicing. This makes it easy to update specific elements or ranges of elements in an array.

arr = np.array([1, 2, 3, 4])
arr[1:3] = 8
print(arr)

[1 8 8 4]


#### How to Access Different Rows of a Multidimensional NumPy Array

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 5, 66],
    [70, 88, 94]
])
print(arr[1])       # middle row
print(arr[[0,2]])   # first & second row
print(arr[:2, :2])  # first 2 rows, first 2 columns

[40  5 66]
[[10 20 30]
 [70 88 94]]
[[10 20]
 [40  5]]


In [ ]:
arr = np.array([
    [[10, 25, 70],
     [30, 45, 55],
     [20, 45, 7]],

    [[50, 65, 8], 
     [70, 85, 10], 
     [11, 22, 33]]
])
# print(arr[:, [1]])
# print(arr[:, [0, 2]])
print(arr[:, :2, :2])

[[[10 25]
  [30 45]]

 [[50 65]
  [70 85]]]


#### Reshape NumPy Array - Python
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
Reshaping in NumPy refers to modifying the dimensions of an existing array without changing its data.
</div>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]*2)
new_arr = arr1.reshape(2, 2, 2)
new_arr = arr2.reshape(2, 3, 3)
print(new_arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(3, -1)
print(new_arr)
# Explanation: This example demonstrates the use of -1 when one dimension is unknown.
# NumPy calculates that missing dimension automatically. arr.reshape(3, -1) tells NumPy 
# to create 3 rows, and it computes the remaining dimension as 4 columns, since 12 ÷ 3 = 4.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Numpy Funtion: numpy.resize()
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
The numpy.resize() function is used to change the size of an existing NumPy array. It modifies the array permanently and adjusts its shape to the new dimensions. If the new shape requires more elements than available, NumPy repeats the array elements. If less space is required, elements are truncated.
</div>

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 3))
print(arr)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr.resize((2, 2))
print(arr)

[[10 20]
 [30 40]]


#### Numpy Funtion: numpy.stack()
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
The numpy.stack() function is used to join multiple arrays by creating a new axis in the output array. This means the resulting array always has one extra dimension compared to the input arrays. To stack arrays, they must have the same shape, and NumPy places them along the axis you specify.
</div>


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
new_arr = np.stack((arr1, arr2), axis=0)
new_arr = np.stack((arr1, arr2), axis=1)
new_arr = np.stack((arr1, arr2), axis=-1)
print(new_arr)
# Explanation:
#   axis= 0: a and b become rows.
#   axis= 1: a and b become columns.
#   axis=-1: same as axis 1 because it refers to the last dimension.

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr2 = np.array(
    [[7, 8, 9],
    [10, 11, 12]
])
print(np.stack((arr1, arr2), axis=2))
# Explanation:
#   axis= 0: stacks arrays as two “layers” of a 3D array.
#   axis= 1: stacks row-wise.
#   axis= 2: stacks column-wise forming 3D structure.

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
arr1 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
arr2 = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])

print(np.stack((arr1, arr2), axis=3))
# Explanation:
#   axis= 0: stacks arrays as two 3D layers.
#   axis= 1: stacks "planes" together.
#   axis= 2: stacks each corresponding row.
#   axis= 3: stacks each corresponding element as a new last-axis pair.

[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


#### Splitting Arrays in NumPy
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
Splitting arrays means dividing a single NumPy array into multiple smaller sub-arrays. NumPy provides several functions that make this easy by allowing you to split arrays along different directions (rows, columns, depth).
<br>
Below are some important terms to understand when splitting arrays:
<br>
Axis: The direction along which the array is split (0 for rows, 1 for columns).
Sub-arrays: Smaller arrays created after splitting the original array.
Splitting Methods: Functions like np.split(), np.hsplit(), np.vsplit() and np.array_split().
Equal vs. Unequal Splits: Splits can divide data evenly, or slightly unevenly if needed (using array_split()).
</div>

#### NumPy Array Broadcasting
<div style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops.
</dib>