#### NumPy - Arithmetic Operations
Arithmetic operations are used for numerical computation and we can perform them on arrays using NumPy.
<div style="font-family: inherit; font-weight: 400; font-size: 16px;  font-style: italic; color: gray;">
1. Addition of Arrays: Add corresponding elements of two arrays using the np.add() function.<br>
2. Subtraction of Arrays: Subtracts each element of the second array from the corresponding element in the first array using the np.subtract() function.<br>
3. Multiplication of Arrays: Multiplies corresponding elements of two arrays using the np.multiply() function.<br>
4. Division of Arrays: Divides each element of the first array by the corresponding element in the second array using the np.divide() function.<br>
5. Exponentiation (Power): It allows us to raise each element in an array to a specified power. In NumPy, this can be done using the np.power() function.<br>
6. Modulus Operation: In NumPy, you can use the np.mod() function to calculate the modulus (remainder) element-wise between two arrays.
</div>

In [15]:
import numpy as np

a = np.array([5, 7, 13, 10])
b = np.array([2, 5, 10, 5])
result = np.add(a, b)
result = np.subtract(a, b)
result = np.multiply(a, b)
result = np.divide(a, b)
result = np.power(a, b)
result = np.mod(a, b)

print(result)

[1 2 3 0]


#### Aggregation Functions:
1. numpy.sum() is a NumPy function used to calculate the sum of array elements.
<pre style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
        Syntax:
        numpy.sum(arr, axis=None, dtype=None, out=None, initial=0, keepdims=False)
        Parameters:
        arr: Input array whose elements are to be summed.
        axis: Axis along which the sum is computed. 0 -> column-wise, 1 -> row-wise and None -> entire array
        dtype: Data type of the returned sum.
        out: Output array to store the result.
        initial: Starting value of the sum.
        keepdims: Keeps the reduced axis as dimension in result.
</pre>






In [16]:
import numpy as np
arr = np.array([5, 10, 15])
print(np.sum(arr))

30


In [17]:
arr = np.array([20, 2, 0.2, 10, 4])
print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))

36.2
36
36.2


In [18]:
arr = np.array([
    [14, 17, 12, 33, 44],
    [15,  6, 27,  8, 19],
    [23,  2, 54,  1,  4]
])

print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=1, keepdims=True))
# Explanation:
#   np.sum(arr, axis=0) column-wise sum.
#   np.sum(arr, axis=1) row-wise sum.
#   np.sum(arr, axis=1, keepdims=True) preserves the reduced dimension, returning a column-shaped result.

279
[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


2. numpy.mean() is used to calculate the arithmetic mean (average) of numeric data.
<pre style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
        Syntax
        numpy.mean(arr, axis=None, dtype=None, out=None)
        Parameters:
        arr: Input array of numbers
        axis (optional): None - mean of all elements, 0 - column-wise mean and 1 - row-wise mean
        dtype (Optional): type used while computing mean
        out (Optional): array to store the result
</pre>

In [19]:
import numpy as np
arr = [20, 2, 7, 1, 34]
res = np.mean(arr)
print(res)

12.8


In [20]:
arr = [
    [14, 17, 12],
    [15,  6, 27],
    [23,  2, 54]
]
print(np.mean(arr))           
print(np.mean(arr, axis=0))   
print(np.mean(arr, axis=1))

18.88888888888889
[17.33333333  8.33333333 31.        ]
[14.33333333 16.         26.33333333]


In [21]:
arr = [
    [5, 10, 15],
    [3,  6,  9],
    [8, 16, 24]
]
res = np.zeros(3)
np.mean(arr, axis=1, out=res)
print(res)

[10.  6. 16.]


3. numpy.maximum() is a NumPy function that compares two arrays (or scalars) element-wise and returns a new array containing the maximum value at each position.
<pre style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
        Syntax
        numpy.maximum(arr1, arr2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None)
        Parameters:
        arr1: First input array (or scalar).
        arr2: Second input array (or scalar).
        out (optional): Array to store the result.
        where: Boolean mask; True positions are computed.
        dtype (optional): Data type of the output.
        casting / order: Controls data casting and memory layout (rarely used).
</pre>

In [23]:
import numpy as np
a = 10
b = 21
print(np.maximum(a, b))

21


In [25]:
arr1 = np.array([2, 8, 125])
arr2 = np.array([3, 3, 15])
print(np.maximum(arr1, arr2))

[  3   8 125]


In [26]:
arr1 = np.array([np.nan, 0, np.nan])
arr2 = np.array([np.nan, np.nan, 0])
print(np.maximum(arr1, arr2))

[nan nan nan]


In [28]:
arr1 = np.array([[1, 4, 7], [2, 5, 8]])
arr2 = np.array([3, 3, 3])
print(np.maximum(arr1, arr2))
# Explanation:
#   b is broadcast across rows.
#   np.maximum(a, b) compares each column with [3, 3, 3].

[[3 4 7]
 [3 5 8]]


4. numpy.minimum() is a NumPy function that compares two arrays (or scalars) element-wise and returns a new array containing the minimum value at each position.
<pre style="font-family: inherit; font-weight: 400; font-size: 16px; font-style: italic; color: gray;">
        Syntax
        numpy.minimum(arr1, arr2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None)
        Parameters:
        arr1: First input array (or scalar).
        arr2: Second input array (or scalar).
        out: Optional array to store output.
        where: Boolean mask; only True positions are computed.
        dtype (optional): Data type of output.
        casting / order: Controls casting and memory layout (advanced use).
</pre>

In [30]:
import numpy as np
a = 10
b = 21
print(np.minimum(a, b))

10


In [32]:
arr1 = np.array([2, 8, 125])
arr2 = np.array([3, 3, 15])
print(np.minimum(arr1, arr2))

[ 2  3 15]


In [33]:
arr1 = np.array([np.nan, 0, np.nan])
arr2 = np.array([np.nan, np.nan, 0])
print(np.minimum(arr1, arr2))

[nan nan nan]


In [35]:
arr1 = np.array([[4, 7, 9], [1, 5, 8]])
arr2 = np.array([3, 6, 10])
print(np.minimum(arr1, arr2))
# Explanation:
#   a2 is broadcast across each row.
#   np.minimum(a1, a2) compares each column pair.

[[3 6 9]
 [1 5 8]]


#### NumPy ufuncs | Universal functions

#### Mathematical Function - NumPy